import type { Component } from 'vue'
import {
  Activity,
  Archive,
  BadgeCheck,
  Banknote,
  Bell,
  Blocks,
  BookOpenText,
  BriefcaseBusiness,
  Building,
  Building2,
  CalendarDays,
  ChartColumn,
  ChartLine,
  ChartPie,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clock,
  Cloud,
  Cog,
  CreditCard,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode2,
  FileImage,
  FilePenLine,
  FileText,
  Filter,
  Folder,
  Frame,
  Gauge,
  Globe2,
  Grid2X2,
  Home,
  Inbox,
  Info,
  KeyRound,
  LayoutDashboard,
  ListTree,
  LockKeyhole,
  LockKeyholeOpen,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  MonitorCog,
  Moon,
  MoreHorizontal,
  Package,
  PanelLeft,
  Pencil,
  Phone,
  Receipt,
  RefreshCw,
  Search,
  Send,
  Server,
  Settings,
  Settings2,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Star,
  Store,
  Sun,
  TableProperties,
  Tag,
  Trash2,
  TriangleAlert,
  Truck,
  UploadCloud,
  UserCheck,
  UserCog,
  UserPlus,
  UserRound,
  UsersRound,
  Wallet,
  Wifi,
  Workflow,
  Wrench,
} from '@lucide/vue'

export const ADMIN_ICON_CATEGORIES = [
  'navigation',
  'people',
  'security',
  'communication',
  'content',
  'data',
  'commerce',
  'status',
  'system',
] as const

export type AdminIconCategory = (typeof ADMIN_ICON_CATEGORIES)[number]

export interface AdminIconOption {
  readonly key: string
  readonly lucideName: string
  readonly category: AdminIconCategory
  readonly component: Component
  readonly labelKey: string | null
  readonly isMenuSafe: boolean
}

// AI modified: one static registry now owns selectable and backend-safe icon resolution; arbitrary strings never become component names.
export const ADMIN_ICON_OPTIONS = [
  {
    key: 'dashboard',
    lucideName: 'LayoutDashboard',
    category: 'navigation',
    component: LayoutDashboard,
    labelKey: 'components.selectors.icons.dashboard',
    isMenuSafe: true,
  },
  {
    key: 'home',
    lucideName: 'Home',
    category: 'navigation',
    component: Home,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'menus',
    lucideName: 'ListTree',
    category: 'navigation',
    component: ListTree,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'components',
    lucideName: 'Blocks',
    category: 'navigation',
    component: Blocks,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'search',
    lucideName: 'Search',
    category: 'navigation',
    component: Search,
    labelKey: 'components.selectors.icons.search',
    isMenuSafe: false,
  },
  {
    key: 'external',
    lucideName: 'ExternalLink',
    category: 'navigation',
    component: ExternalLink,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'iframe',
    lucideName: 'Frame',
    category: 'navigation',
    component: Frame,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'globe',
    lucideName: 'Globe2',
    category: 'navigation',
    component: Globe2,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'location',
    lucideName: 'MapPin',
    category: 'navigation',
    component: MapPin,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'panel',
    lucideName: 'PanelLeft',
    category: 'navigation',
    component: PanelLeft,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'grid',
    lucideName: 'Grid2X2',
    category: 'navigation',
    component: Grid2X2,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'more',
    lucideName: 'MoreHorizontal',
    category: 'navigation',
    component: MoreHorizontal,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'users',
    lucideName: 'UsersRound',
    category: 'people',
    component: UsersRound,
    labelKey: 'components.selectors.icons.users',
    isMenuSafe: true,
  },
  {
    key: 'profile',
    lucideName: 'UserRound',
    category: 'people',
    component: UserRound,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'departments',
    lucideName: 'Building2',
    category: 'people',
    component: Building2,
    labelKey: 'components.selectors.icons.departments',
    isMenuSafe: true,
  },
  {
    key: 'positions',
    lucideName: 'BriefcaseBusiness',
    category: 'people',
    component: BriefcaseBusiness,
    labelKey: 'components.selectors.icons.positions',
    isMenuSafe: true,
  },
  {
    key: 'organization',
    lucideName: 'Building',
    category: 'people',
    component: Building,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'user-add',
    lucideName: 'UserPlus',
    category: 'people',
    component: UserPlus,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'user-check',
    lucideName: 'UserCheck',
    category: 'people',
    component: UserCheck,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'user-settings',
    lucideName: 'UserCog',
    category: 'people',
    component: UserCog,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'permissions',
    lucideName: 'ShieldCheck',
    category: 'security',
    component: ShieldCheck,
    labelKey: 'components.selectors.icons.permissions',
    isMenuSafe: false,
  },
  {
    key: 'roles',
    lucideName: 'ShieldCheck',
    category: 'security',
    component: ShieldCheck,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'password',
    lucideName: 'KeyRound',
    category: 'security',
    component: KeyRound,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'lock',
    lucideName: 'LockKeyhole',
    category: 'security',
    component: LockKeyhole,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'unlock',
    lucideName: 'LockKeyholeOpen',
    category: 'security',
    component: LockKeyholeOpen,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'security-alert',
    lucideName: 'ShieldAlert',
    category: 'security',
    component: ShieldAlert,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'visible',
    lucideName: 'Eye',
    category: 'security',
    component: Eye,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'hidden',
    lucideName: 'EyeOff',
    category: 'security',
    component: EyeOff,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'notifications',
    lucideName: 'Bell',
    category: 'communication',
    component: Bell,
    labelKey: 'components.selectors.icons.notifications',
    isMenuSafe: false,
  },
  {
    key: 'message-center',
    lucideName: 'Bell',
    category: 'communication',
    component: Bell,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'mail',
    lucideName: 'Mail',
    category: 'communication',
    component: Mail,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'message',
    lucideName: 'MessageSquare',
    category: 'communication',
    component: MessageSquare,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'send',
    lucideName: 'Send',
    category: 'communication',
    component: Send,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'phone',
    lucideName: 'Phone',
    category: 'communication',
    component: Phone,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'content-admin',
    lucideName: 'Megaphone',
    category: 'communication',
    component: Megaphone,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'inbox',
    lucideName: 'Inbox',
    category: 'communication',
    component: Inbox,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'connection',
    lucideName: 'Wifi',
    category: 'communication',
    component: Wifi,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'documents',
    lucideName: 'FileText',
    category: 'content',
    component: FileText,
    labelKey: 'components.selectors.icons.documents',
    isMenuSafe: false,
  },
  {
    key: 'form-workbench',
    lucideName: 'FilePenLine',
    category: 'content',
    component: FilePenLine,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'dictionaries',
    lucideName: 'BookOpenText',
    category: 'content',
    component: BookOpenText,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'folder',
    lucideName: 'Folder',
    category: 'content',
    component: Folder,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'image',
    lucideName: 'FileImage',
    category: 'content',
    component: FileImage,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'code',
    lucideName: 'FileCode2',
    category: 'content',
    component: FileCode2,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'archive',
    lucideName: 'Archive',
    category: 'content',
    component: Archive,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'calendar',
    lucideName: 'CalendarDays',
    category: 'content',
    component: CalendarDays,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'tag',
    lucideName: 'Tag',
    category: 'content',
    component: Tag,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'edit',
    lucideName: 'Pencil',
    category: 'content',
    component: Pencil,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'database',
    lucideName: 'Database',
    category: 'data',
    component: Database,
    labelKey: 'components.selectors.icons.database',
    isMenuSafe: false,
  },
  {
    key: 'analytics',
    lucideName: 'ChartColumn',
    category: 'data',
    component: ChartColumn,
    labelKey: 'components.selectors.icons.analytics',
    isMenuSafe: false,
  },
  {
    key: 'chart-line',
    lucideName: 'ChartLine',
    category: 'data',
    component: ChartLine,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'chart-pie',
    lucideName: 'ChartPie',
    category: 'data',
    component: ChartPie,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'gauge',
    lucideName: 'Gauge',
    category: 'data',
    component: Gauge,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'activity',
    lucideName: 'Activity',
    category: 'data',
    component: Activity,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'filter',
    lucideName: 'Filter',
    category: 'data',
    component: Filter,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'table',
    lucideName: 'TableProperties',
    category: 'data',
    component: TableProperties,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'workflow',
    lucideName: 'Workflow',
    category: 'data',
    component: Workflow,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'monitoring',
    lucideName: 'MonitorCog',
    category: 'data',
    component: MonitorCog,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'server',
    lucideName: 'Server',
    category: 'data',
    component: Server,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'cart',
    lucideName: 'ShoppingCart',
    category: 'commerce',
    component: ShoppingCart,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'package',
    lucideName: 'Package',
    category: 'commerce',
    component: Package,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'wallet',
    lucideName: 'Wallet',
    category: 'commerce',
    component: Wallet,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'money',
    lucideName: 'Banknote',
    category: 'commerce',
    component: Banknote,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'store',
    lucideName: 'Store',
    category: 'commerce',
    component: Store,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'delivery',
    lucideName: 'Truck',
    category: 'commerce',
    component: Truck,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'receipt',
    lucideName: 'Receipt',
    category: 'commerce',
    component: Receipt,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'payment',
    lucideName: 'CreditCard',
    category: 'commerce',
    component: CreditCard,
    labelKey: null,
    isMenuSafe: false,
  },

  {
    key: 'success',
    lucideName: 'CircleCheck',
    category: 'status',
    component: CircleCheck,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'warning',
    lucideName: 'TriangleAlert',
    category: 'status',
    component: TriangleAlert,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'error',
    lucideName: 'CircleX',
    category: 'status',
    component: CircleX,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'alert',
    lucideName: 'CircleAlert',
    category: 'status',
    component: CircleAlert,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'info',
    lucideName: 'Info',
    category: 'status',
    component: Info,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'pending',
    lucideName: 'Clock',
    category: 'status',
    component: Clock,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'favorite',
    lucideName: 'Star',
    category: 'status',
    component: Star,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'verified',
    lucideName: 'BadgeCheck',
    category: 'status',
    component: BadgeCheck,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'help',
    lucideName: 'CircleHelp',
    category: 'status',
    component: CircleHelp,
    labelKey: 'components.selectors.icons.help',
    isMenuSafe: false,
  },

  {
    key: 'settings',
    lucideName: 'Settings',
    category: 'system',
    component: Settings,
    labelKey: 'components.selectors.icons.settings',
    isMenuSafe: false,
  },
  {
    key: 'system-config',
    lucideName: 'Settings2',
    category: 'system',
    component: Settings2,
    labelKey: null,
    isMenuSafe: true,
  },
  {
    key: 'cog',
    lucideName: 'Cog',
    category: 'system',
    component: Cog,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'tools',
    lucideName: 'Wrench',
    category: 'system',
    component: Wrench,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'cloud',
    lucideName: 'Cloud',
    category: 'system',
    component: Cloud,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'upload',
    lucideName: 'UploadCloud',
    category: 'system',
    component: UploadCloud,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'download',
    lucideName: 'Download',
    category: 'system',
    component: Download,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'refresh',
    lucideName: 'RefreshCw',
    category: 'system',
    component: RefreshCw,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'delete',
    lucideName: 'Trash2',
    category: 'system',
    component: Trash2,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'theme',
    lucideName: 'Sun',
    category: 'system',
    component: Sun,
    labelKey: null,
    isMenuSafe: false,
  },
  {
    key: 'dark-mode',
    lucideName: 'Moon',
    category: 'system',
    component: Moon,
    labelKey: null,
    isMenuSafe: false,
  },
] as const satisfies readonly AdminIconOption[]

export type AdminIconKey = (typeof ADMIN_ICON_OPTIONS)[number]['key']

export const UNKNOWN_ADMIN_ICON_COMPONENT: Component = CircleHelp

const adminIconOptionsByKey = new Map<string, AdminIconOption>(
  ADMIN_ICON_OPTIONS.map((option) => [option.key, option]),
)

export function getAdminIconOption(iconKey: string | undefined): AdminIconOption | undefined {
  return iconKey ? adminIconOptionsByKey.get(iconKey) : undefined
}

export function getAdminIconComponent(iconKey: string | undefined): Component {
  // AI modified: unknown backend keys stop at an explicit local fallback instead of being resolved as dynamic imports or global components.
  return getAdminIconOption(iconKey)?.component ?? UNKNOWN_ADMIN_ICON_COMPONENT
}

export function isAdminIconKey(iconKey: string): iconKey is AdminIconKey {
  return adminIconOptionsByKey.has(iconKey)
}
